name: Test composite action
on:
  pull_request:
    paths:
      - 'action.yml'
  workflow_dispatch:    

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test action
        uses: ./
        with:
          cache: 'true'
          
      - name: Check that a fake module can be built
        working-directory: .github/workflows
        run: make
  
  test-composite-action-cached:
    runs-on: ubuntu-latest
    needs: test-composite-action
    steps:
      - uses: actions/checkout@v4
      
      - name: Store KERNEL_RELEASE
        shell: bash
        run: |
          echo "KERNEL_RELEASE=$(uname -r)" >> $GITHUB_ENV
    
      - name: Test that kernel sources are cached
        uses: actions/cache@v4
        with:
          path: |
            /usr/src/linux
          key: ${{ runner.os }}-${{ runner.arch }}-${{env.KERNEL_RELEASE}}
          
      - name: Fully restore through action
        uses: ./
        with:
          cache: 'true'
      
      - name: Check that a fake module can be built again
        working-directory: .github/workflows
        run: make
